### ISSUE TITLE
getOfferings() response empty?

### ISSUE THREAD

**Issue by jkeen** [riderx/capacitor-purchases#1]
First off, thanks for forking and creating this capacitor plugin! It came at the perfect time in our app development.

I can't seem to get the offerings call to return anything though, despite having offerings and entitlements set up in Revenue Cat. Not sure if this is a bug in this plugin, something I'm doing wrong, or something I need to contact RevenueCat support about? 

Am I using this correctly?
```js

import { CapacitorPurchases } from 'capacitor-purchases';

CapacitorPurchases.setDebugLogsEnabled({ enabled: true });
await CapacitorPurchases.setup({ apiKey: API_KEY });
let { offerings } = await CapacitorPurchases.getOfferings();
console.log(offerings) // => {}

```

**Comment by riderx** [comment]
in both android and ios ? 
i use it my app and don't have this issue

**Comment by riderx** [comment]
@jkeen did you have special price in your offering ?
i got the same issue 2 days ago and fixed it, is was json conversion issue, can you check ?

**Comment by jkeen** [comment]
Looks like that was it, offerings now loading correctly 👍🏻
