### ISSUE TITLE
compile against version 32 or later of the

### ISSUE THREAD

**Issue by productdevbook** [riderx/capacitor-purchases#3]
https://github.com/riderx/capacitor-purchases/blob/c09243ff909dc8942c76709f9385e5339b5cc8c6/android/build.gradle#L61

```

  1.  Dependency 'androidx.core:core:1.9.0-alpha05' requires libraries and applications that
      depend on it to compile against version 32 or later of the
      Android APIs.

      :app is currently compiled against android-31.

      Recommended action: Update this project to use a newer compileSdkVersion
      of at least 32, for example 32.
```

ionic used 1.7.0

![image](https://user-images.githubusercontent.com/38668796/174490391-73800dd3-c0d1-4ab1-b91f-3600679db850.png)

_i think you need to sync this to user's config file_

**Comment by riderx** [comment]
@productdevbook thanks for the report i accepted your Pr but by the way why not upgrade to sdk 32 as asked

**Comment by productdevbook** [comment]
Because capacitor v3 not now 12 support. V4.beta support. Feature.

**Comment by productdevbook** [comment]
https://github.com/ionic-team/capacitor/releases/tag/4.0.0-beta.0

**Comment by productdevbook** [comment]
dont forget npm version update :)

**Comment by riderx** [comment]
@productdevbook totally forgot, time to setup the auto-publish CI like other plugins :)

**Comment by riderx** [comment]
Publish done, CI setup https://github.com/riderx/capacitor-purchases/actions/runs/2530301350
